# Generated by Django 4.0.1 on 2022-01-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('modelo', models.IntegerField(default=0)),
                ('marca', models.CharField(default='N/A', max_length=128)),
                ('placa', models.CharField(default='Sin Registro', max_length=128, primary_key=True, serialize=False)),
            ],
        ),
    ]
